version: "3.9"
services:
    db:
        build:
            context: .
            dockerfile: db.dockerfile
        container_name: time-clock-react-db_v.0.1.0
        image: node_16_time_clock_db
        working_dir: /usr/app/time-clock
        command: npm run timeclock:db
        volumes:
            - ./:/usr/app/time-clock/
            - ./node_modules:/usr/app/time-clock/node_modules
        expose:
            - "3001"
        ports:
            - "3001:3001"

    app:
        build:
            context: .
            dockerfile: app.dockerfile
        container_name: time-clock-react_v.0.1.0
        image: node_16_time_clock
        working_dir: /usr/app/time-clock
        command: npm run timeclock:project
        stdin_open: true
        environment:
            - CI=true
            - CHOKIDAR_USEPOLLING=true
        tty: true
        volumes:
            - ./:/usr/app/time-clock/
            - node_modules:/usr/app/time-clock/node_modules
        expose: 
            - "3000"
        ports:
            - "3000:3000"
        links: 
            - db
volumes: 
    node_modules:

