version: "3.9"
services:
    db:
        build: .
        image: node:16-alpine
        container_name: time-clock-react-db_v.0.1.0
        working_dir: /usr/app/time-clock
        command: npm run timeclock:db
        volumes:
            - ./:/usr/app/time-clock/
        expose:
            - "3001"
        ports:
            - "3001:3001"

    app:
        image: node:16-alpine
        container_name: time-clock-react_v.0.1.0
        working_dir: /usr/app/time-clock
        command: npm run timeclock:project
        stdin_open: true
        environment:
            - CI=true
            - CHOKIDAR_USEPOLLING=true
        tty: true
        volumes:
            - ./:/usr/app/time-clock/
            - /usr/app/time-clock/node_modules
        expose: 
            - "3000"
        ports:
            - "3000:3000"
        depends_on: 
            - db


